### ISSUE TITLE
update to new API version

### ISSUE THREAD

**Issue by chronoB** [vigonotion/pygti#17]
API version 38 was released in march. 
- Update examples to use API 38 instead of 37.

Question: 
- In the auth.py file in l. 40 you update the version in the payload. I couldn't find any documentation in the Voluptuous Readme about updating a schema. Does it add the parameter "version" if it is not there or does it update the parameter to be 37 all the time? 
I think it would be good to then have an optional version number in the requests and if the user adds one to specify the version it should be prioritized over the standard. Also a way to set the standard version via a higher level function could be a good thing.

**Comment by vigonotion** [comment]
We should always update all methods to the new API version. Then, only one API version is needed and avoids confusion. Do you have an example of a request that **only** works with an older API version? The update is not part of voluptuous, the payload is just a python dictionary. You can call update on a dictionary to update it's elements.

Setting a standard version somewhere would break our API implementation, e. g. because parameters mismatch between versions, and as I said above I don't see a benefit of allowing the user to change the api version?

**Comment by chronoB** [comment]
Yeah, you are probably right about updating all methods to the new API version. But then it is misleading that the version parameter can be specified by the user (when it has no impact after all).

**Comment by vigonotion** [comment]
Good point, then let's remove the version parameter

**Comment by chronoB** [comment]
closed by dbebaedab19610e4efd03ca957e29bd725676b66
